"""Calibrated camera rig presets and matched lens catalog."""

from __future__ import annotations
from typing import Any, Dict

LENS_CATALOG: dict[str, list[str]] = {
    "sony_a1_ii": [
        "Sony FE 85mm F1.4 GM II (SEL85F14GM2) [High Hit-Rate Portrait]",
        "Sony FE 50mm F1.2 GM (SEL50F12GM) [Environmental Micro-Contrast]",
        "Sony FE 135mm F1.8 GM (SEL135F18GM) [Compression Texture Monster]",
    ],
    "canon_eos_r5_ii": [
        "Canon RF 85mm F1.2L USM (Reference Portrait Prime)",
        "Canon RF 100mm f/2.8L Macro IS USM (1.4x Focus-Stacked Macro)",
        "Canon RF 50mm F1.2L USM (Micro-Contrast & Natural DOF)",
        "Canon RF 135mm F1.8L IS USM (Subject Separation & IS)",
    ],
    "nikon_z9": [
        "NIKKOR Z 600mm f/4 TC VR S @ 840mm f/5.6 (Super-Telephoto Wildlife Compression)",
        "NIKKOR Z 135mm f/1.8 S Plena (Zero Vignetting Texture Monster)",
        "NIKKOR Z 85mm f/1.2 S (Reference Portrait Prime)",
        "NIKKOR Z 50mm f/1.2 S (High-Acutance Standard)",
    ],
    "phase_one_iq4": [
        "Schneider Kreuznach 110mm LS f/2.8 Blue Ring (Portrait Compression & Maximum Resolving Authority)",
        "Schneider Kreuznach 120mm LS f/4 Macro (1:1 Beauty Macro, Lips & Lashes)",
        "Schneider Kreuznach 80mm LS f/2.8 Blue Ring (Standard Reference)",
        "Schneider Kreuznach 55mm LS f/2.8 Blue Ring (Wide Architectural)",
        "Schneider Kreuznach 150mm LS f/3.5 Blue Ring (Tight Portrait)",
        "Schneider Kreuznach 240mm LS f/4.5 (Telephoto Separation)",
    ],
    "module_a": [
        "Schneider Kreuznach 110mm LS f/2.8 Blue Ring (Portrait Compression & Maximum Resolving Authority)",
        "Schneider Kreuznach 80mm LS f/2.8 Blue Ring (Standard Reference)",
        "Schneider Kreuznach 120mm LS f/4 Macro (1:1 Beauty Macro)",
    ],
    "module_b": [
        "Hasselblad XCD 2.5/90V (Reference Medium Format Portrait Prime)",
        "Hasselblad XCD 55mm f/2.5 V (High-Resolution Normal)",
        "Hasselblad XCD 38mm f/2.5 V (Environmental Wide)",
    ],
    "module_c": [
        "Fujinon GF 110mm f/2 R LM WR (Reference 87mm Portrait Prime)",
        "Fujinon GF 80mm f/1.7 R WR (Ultra-Fast Medium Format)",
        "Fujinon GF 55mm f/1.7 R WR (Natural Standard)",
    ],
    "hasselblad_h6d": [
        "Hasselblad HC 100mm f/2.2 Portrait Lens (Reference Prime)",
        "Hasselblad HC 50mm f/3.5 II Wide Angle",
        "Hasselblad HC 150mm f/3.2 Telephoto",
        "Hasselblad HC 24mm f/4.8 Ultra-Wide",
    ],
    "hasselblad_500cm": [
        "Carl Zeiss Planar T* 80mm f/2.8 CF (Legendary Standard)",
        "Carl Zeiss Distagon T* 50mm f/4 CF (Wide Street & Interior)",
        "Carl Zeiss Sonnar T* 150mm f/4 CF (Classic Portrait)",
        "Carl Zeiss Biogon T* 38mm f/4.5 (Distortion-Free Wide)",
    ],
    "pentax_67ii": [
        "SMC Pentax 67 105mm f/2.4 (The Legendary Bokeh King)",
        "SMC Pentax 67 90mm f/2.8 (Crisp Documentary Normal)",
        "SMC Pentax 67 55mm f/4 (Deep Landscape & Interior)",
        "SMC Pentax 67 165mm f/2.8 (Velvety Compression)",
    ],
    "linhof_technika_4x5": [
        "Schneider Kreuznach Apo-Symmar 150mm f/5.6 L (Museum Reference)",
        "Rodenstock Grandagon-N 90mm f/4.5 (Extreme Architectural Rise)",
        "Schneider Super-Angulon 72mm f/5.6 XL (Ultra-Wide Interior)",
        "Schneider Apo-Tele-Xenar 250mm f/5.6 (Fine Art Telephoto)",
    ],
    "leica_m11": [
        "Leica Summilux-M 35mm f/1.4 ASPH FLE II (Documentary Reference)",
        "Leica Summilux-M 35mm f/1.4 ASPH II (Photojournalism Reference)",
        "Leica Noctilux-M 50mm f/0.95 ASPH (The King of Light)",
        "Leica Noctilux-M 75mm f/1.25 ASPH (Low-Light Portrait Bokeh King)",
        "Leica APO-Summicron-M 50mm f/2 ASPH (Benchmark Optical Acutance)",
        "Leica APO-Summicron-M 90mm f/2 ASPH (Telephoto Benchmark Acutance)",
        "Leica Summicron-M 28mm f/2 ASPH (Environmental Reportage)",
    ],
    "leica_m6_analog": [
        "Leica Summilux-M 35mm f/1.4 Pre-ASPH 'Steel Rim'",
        "Leica Summilux-M 35mm f/1.4 ASPH II (Modern Aspherical Optical Purity)",
        "Leica Summicron-M 50mm f/2 Dual-Range (Classic German Micro-Contrast)",
        "Leica APO-Summicron-M 50mm f/2 ASPH (Apochromatic Reference)",
        "Leica Noctilux-M 75mm f/1.25 ASPH (Low-Light Character Prime)",
        "Leica APO-Summicron-M 90mm f/2 ASPH (Analog Telephoto Benchmark)",
        "Leica Summicron-M 28mm f/2 ASPH (Environmental Reportage)",
        "Leica Elmarit-M 28mm f/2.8 (Compact Street)",
        "Leica Tele-Elmarit-M 90mm f/2.8 'Fat Elmarit'",
    ],
    "arri_alexa_35": [
        "Cooke S4/i 50mm T2.0 Cine Prime ('The Cooke Look')",
        "ARRI Signature Prime 47mm T1.8 (Organic Warm Skin Tones)",
        "Atlas Orion 65mm T2.0 2x Anamorphic Prime (Oval Bokeh & Horizontal Flare)",
        "Angenieux Optimo Ultra 12x Cine Zoom (Feature Film)",
    ],
    "fujifilm_gfx100ii": [
        "Fujinon GF 30mm f/5.6 T/S (Perspective-Control Shift Lens)",
        "Fujinon GF 110mm f/2 R LM WR (Reference Portrait Prime)",
        "Fujinon GF 80mm f/1.7 R WR (Ultra-Fast Medium Format)",
        "Fujinon GF 55mm f/1.7 R WR (Natural Standard)",
        "Fujinon GF 250mm f/4 R LM OIS WR (Subject Isolation)",
    ],
    "sony_a7rv": [
        "Sony FE 90mm f/2.8 Macro G OSS (1:1 Micro-Bench Reproduction)",
        "Sony FE 50mm f/1.2 GM (G-Master Optical Reference)",
        "Sony FE 85mm f/1.4 GM II (Portrait Specialist)",
        "Sony FE 135mm f/1.8 GM (Razor-Sharp Background Dissolution)",
        "Sony FE 24-70mm f/2.8 GM II (Versatile Commercial Standard)",
    ],
    "sony_fx_series": [
        "Sony FE 50mm f/1.2 GM @ f/2.8 (Venice Cine Sweet Spot)",
        "Sony FE 24-70mm f/2.8 GM II (Versatile Cine Zoom)",
        "Sony FE 85mm f/1.4 GM II (Cinematic Portrait Prime)",
        "Sony FE 135mm f/1.8 GM (Cinematic Separation Prime)",
        "Sony FE 16-35mm f/2.8 GM II (Wide Cine Master)",
    ],
    "hasselblad_x2d_ii_100c": [
        "Hasselblad XCD 90mm f/2.5 V (Reference Medium Format Portrait Prime)",
        "Hasselblad XCD 55mm f/2.5 V (High-Resolution Normal)",
        "Hasselblad XCD 38mm f/2.5 V (Environmental Wide)",
        "Hasselblad XCD 135mm f/2.8 with 1.7x Converter",
    ],
    "fujifilm_gfx100rf": [
        "Fujinon GF 45mm f/2.8 R WR (Compact Documentary Prime)",
        "Fujinon GF 63mm f/2.8 R WR (Standard Rangefinder Normal)",
        "Fujinon GF 110mm f/2 R LM WR (Reference Portrait Prime)",
        "Fujinon GF 30mm f/3.5 R WR (Wide Street Architecture)",
    ],
    "canon_eos_r1": [
        "Canon RF 85mm F1.2L USM (Reference Portrait & Decisive Action)",
        "Canon RF 70-200mm F2.8L IS USM Z (Action & Sports Master)",
        "Canon RF 400mm F2.8L IS USM (Super-Telephoto Action)",
        "Canon RF 24-70mm F2.8L IS USM (Universal Fast Zoom)",
    ],
    "leica_sl3_p": [
        "Leica APO-Summicron-SL 50mm f/2 ASPH (Apochromatic Benchmark)",
        "Leica APO-Summicron-SL 75mm f/2 ASPH (Portrait Micro-Contrast)",
        "Leica APO-Summicron-SL 90mm f/2 ASPH (Benchmark Telephoto Acutance)",
        "Leica APO-Summicron-SL 35mm f/2 ASPH (Environmental Documentary)",
        "Leica Super-Vario-Elmar-SL 16-35mm f/3.5-4.5 ASPH",
    ],
    "leica_q3_monochrom": [
        "Leica Summilux 28mm f/1.7 ASPH (Fixed Integrated Lens with Macro Mode)",
        "Leica Summilux 28mm f/1.7 ASPH @ Macro Mode (17cm close focus)",
        "Leica Summilux 28mm f/1.7 ASPH (35mm Crop Mode)",
        "Leica Summilux 28mm f/1.7 ASPH (50mm Crop Mode)",
        "Leica Summilux 28mm f/1.7 ASPH (75mm Crop Mode)",
        "Leica Summilux 28mm f/1.7 ASPH (90mm Crop Mode)",
    ],
    "panasonic_lumix_s1rii": [
        "Lumix S PRO 50mm f/1.4 Leica-Certified (Ultimate Optical Purity)",
        "Lumix S PRO 85mm f/1.8 (Lightweight Portrait Prime)",
        "Lumix S 100mm f/2.8 Macro (1:1 Micro-Detail Specialist)",
        "Lumix S PRO 24-70mm f/2.8 (Professional Documentary Standard)",
    ],
    "leica_sl2": [
        "Leica Summilux-SL 50mm f/1.4 ASPH (Motion-Blur Crowd Reference)",
        "Leica APO-Summicron-SL 35mm f/2 ASPH (Environmental Reportage)",
        "Leica APO-Summicron-SL 75mm f/2 ASPH (Portrait Acutance)",
        "Leica APO-Summicron-SL 90mm f/2 ASPH (Telephoto Acutance)",
        "Leica Super-Vario-Elmar-SL 16-35mm f/3.5-4.5 ASPH (Architectural Street)",
    ],
    "imax_msm_9802": [
        "IMAX 65mm Large-Format Prime Lens",
        "IMAX 65mm 50mm T2.8 Motion Picture Lens",
        "IMAX 65mm 80mm T2.8 Motion Picture Lens",
    ],
    "arri_alexa_265": [
        "ARRI Rental Prime 65 S 50mm T1.8 (65mm Sensor Vista Prime)",
        "ARRI Rental Prime 65 S 35mm T2.5 (65mm Wide Cinema Vista)",
        "ARRI Rental Prime 65 S 80mm T1.8 (65mm Portrait Compression)",
    ],
    "nikon_fm2": [
        "AI-S Nikkor 105mm f/2.5 (Legendary Available-Light Portrait Prime)",
        "AI-S Nikkor 50mm f/1.4 (Classic Mechanical Standard)",
        "AI-S Nikkor 35mm f/2 (Photojournalism Wide)",
    ],
    "contax_645": [
        "Carl Zeiss Planar T* 80mm f/2 (Legendary High-Key Medium Format Prime)",
        "Carl Zeiss Distagon T* 45mm f/2.8 (Wide Environmental)",
        "Carl Zeiss Sonnar T* 140mm f/2.8 (Portrait Telephoto)",
    ],
    "hasselblad_xpan": [
        "Hasselblad 45mm f/4 for XPan (2.7:1 Panoramic Landscape Standard)",
        "Hasselblad 30mm f/5.6 for XPan (Ultra-Wide 2.7:1 Panoramic)",
        "Hasselblad 90mm f/4 for XPan (Telephoto 2.7:1 Panoramic)",
    ],
    "deardorff_8x10": [
        "Schneider Kreuznach Symmar-S 360mm f/6.8 (8x10 Large-Format Portrait Prime)",
        "Rodenstock Apo-Ronar 300mm f/9 (Large-Format Process Acutance)",
        "Goerz Dagor 12-inch (305mm) f/6.8 (Classic Large-Format Tone)",
    ],
    "antique_view_8x10": [
        "Uncoated Brass Petzval Lens ~300mm f/3.8 (Swirling Bokeh & Vignette Falloff)",
        "Uncoated Rapid Rectilinear Brass Lens ~350mm f/8 (Wet-Plate Period Standard)",
    ],
    "contax_t2": [
        "Carl Zeiss Sonnar T* 38mm f/2.8 (Fixed Titanium Compact Lens)",
    ],
    "ricoh_gr_iv": [
        "GR Lens 18.3mm f/2.8 (28mm equivalent Snap Focus Prime)",
    ],
    "dji_mavic_4_pro": [
        "Hasselblad 28mm-equivalent f/2.8 Aerial Optics (Nadir Geometry Prime)",
        "Hasselblad 70mm-equivalent Telephoto Aerial Camera",
        "Hasselblad 166mm-equivalent Super-Telephoto Aerial Camera",
    ],
    "mamiya_rz67": [
        "Mamiya Sekor Z 140mm f/4.5 Macro (Close-Up Character Portrait Specialist)",
        "Mamiya Sekor Z 110mm f/2.8 (Standard Normal Prime)",
        "Mamiya Sekor Z 65mm f/4 L-A (Wide Environmental)",
    ],
    "polaroid_20x24": [
        "Schneider 600mm f/11 for Polaroid 20x24 (Life-Size 1:1 Contact Lens)",
        "Schneider 300mm f/5.6 for Polaroid 20x24 (Environmental Contact Lens)",
    ],
}

CAMERA_PRESETS: dict[str, dict[str, Any]] = {
    # 0. Verified Medium Format Photographic Signatures (Tri-Signature Suite)
    "cam_module_a_phase_one_110mm": {
        "profile": "phase_one_iq4",
        "lens": "Schneider Kreuznach 110mm LS f/2.8 Blue Ring",
        "aperture": "f/8.0",
        "subject": "Bespoke Savile Row tailor measuring a client, tactile wool tweed weave, individual thread fibers, chalk markings, and dimensional micro-relief",
        "framing": "three-quarter editorial body portrait",
        "environment": "Mayfair tailoring atelier with dark mahogany fitting stalls, cutting shears, and soft natural directional window strobe",
        "wardrobe": "charcoal wool flannel three-piece suit with mother-of-pearl buttons",
        "mood": "Module A resolving authority, 151MP BSI medium format precision, authentic epidermal skin texture and unyielding textile weave",
        "timeWeather": "auto",
        "lighting": "strobe_para",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
        "universalMediumFormatOverride": True,
    },
    "cam_module_b_hasselblad_90v": {
        "profile": "hasselblad_x2d_ii_100c",
        "lens": "Hasselblad XCD 2.5/90V",
        "aperture": "f/5.6",
        "subject": "Ballet dancer seated in repose by limestone arched window, nuanced porcelain skin tones, satin ribbons, and luminous specular highlights",
        "framing": "full-body editorial portrait",
        "environment": "historic rehearsal hall with sunlit lime-washed stone walls and aged oak herringbone floor",
        "wardrobe": "silk tulle rehearsal wrap and pink satin pointe shoes",
        "mood": "Module B tonal realism, 100MP HNCS 16-bit color depth, luminous highlight roll-off, and deep chromatically intact shadow modeling",
        "timeWeather": "golden_hour",
        "lighting": "golden_hour",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
        "universalMediumFormatOverride": True,
    },
    "cam_module_c_fujifilm_110mm": {
        "profile": "fujifilm_gfx100ii",
        "lens": "Fujinon GF 110mm f/2 R LM WR",
        "aperture": "f/5.6",
        "subject": "High-fashion model standing poised in structured architectural overcoat, natural 87mm perspective compression and crisp focal-plane eyelashes",
        "framing": "three-quarter body fashion portrait",
        "environment": "brutalist minimalist concrete pavilion with soft directional daylight and subtle negative fill",
        "wardrobe": "structural camel cashmere double-breasted overcoat and ivory silk scarf",
        "mood": "Module C portrait precision, 102MP CMOS II HS resolving power, 87mm-equivalent compression, and proportional anatomy without telephoto flattening",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "classic_chrome",
        "aspectRatio": "4:5",
        "universalMediumFormatOverride": True,
    },

    # 1. Medium Format Commercial Titans (100MP–150MP)
    "cam_phase_one_iq4_still": {
        "profile": "phase_one_iq4",
        "lens": "Schneider Kreuznach 80mm LS f/2.8 Blue Ring",
        "aperture": "f/8.0",
        "subject": "Fine art museum curator in tailored charcoal wool suit examining a classical marble bust, high tactile micro-relief and chisel marks",
        "framing": "three-quarter museum gallery portrait",
        "environment": "neoclassical museum rotunda with soaring limestone walls and diffuse high clerestory light",
        "wardrobe": "bespoke charcoal three-piece suit with silk pocket square",
        "mood": "timeless archival reverence, museum-grade 150MP resolution",
        "timeWeather": "overcast",
        "lighting": "architectural_skylight",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
        "paperProfile": "baryta",
        "printSize": "16x24@300",
    },
    "cam_phase_one_iq4_arch": {
        "profile": "phase_one_iq4",
        "lens": "Schneider Kreuznach 55mm LS f/2.8 Blue Ring",
        "aperture": "f/8.0",
        "subject": "Architect leaning over a monolithic drafting table reviewing hand-drawn blueprints and raw concrete scale models",
        "framing": "wide environmental architectural portrait",
        "environment": "brutalist board-formed concrete library pavilion with high clerestory windows",
        "wardrobe": "charcoal fine-knit merino turtleneck and tailored trousers",
        "mood": "austere, contemplative, intellectual focus",
        "timeWeather": "overcast",
        "lighting": "architectural_skylight",
        "filmStock": "digital_raw",
        "aspectRatio": "16:9",
    },
    "cam_phase_one_iq4_macro_beauty": {
        "profile": "phase_one_iq4",
        "lens": "Schneider Kreuznach 120mm LS f/4 Macro",
        "aperture": "f/11",
        "subject": "medium format 1:1 macro beauty photograph, extreme close-up of lips and eyelashes, stopped down for depth, razor-sharp pore-level micro-detail, fine vellus hair and lash tips, high-resolution studio clarity, shot on Phase One IQ4 with Schneider 120mm macro",
        "framing": "extreme macro iris and skin detail portrait",
        "environment": "clean neutral studio environment with precision directional key strobe",
        "wardrobe": "none",
        "mood": "150MP Trichromatic macro purity, unyielding epidermal micro-detail, authentic lip vermilion borders and individual lash fibers",
        "timeWeather": "auto",
        "lighting": "strobe_para",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
        "skinLighting": "raking_hard_key",
    },
    "cam_hasselblad_h6d_para": {
        "profile": "hasselblad_h6d",
        "lens": "Hasselblad HC 100mm f/2.2 Portrait Lens",
        "aperture": "f/4.0",
        "subject": "Haute couture fashion model in structural pleated ivory silk gown with razor-sharp gaze",
        "framing": "full-length architectural fashion portrait",
        "environment": "pristine white infinity cove photo studio with subtle floor reflections",
        "wardrobe": "sculptural pleated raw ivory silk architectural dress",
        "mood": "avant-garde, pristine luxury, crystalline micro-contrast",
        "timeWeather": "auto",
        "lighting": "strobe_para",
        "filmStock": "portra_160",
        "aspectRatio": "4:5",
    },
    "cam_hasselblad_x2d_hncs": {
        "profile": "hasselblad_x2d_ii_100c",
        "lens": "Hasselblad XCD 90mm f/2.5 V",
        "aperture": "f/2.5",
        "subject": "Equestrian trainer standing beside a dark thoroughbred in sunlit stone courtyard, tactile leather reins and tweed textures",
        "framing": "three-quarter outdoor editorial portrait",
        "environment": "historic limestone stables courtyard with sun-warmed cobblestones and horse brasses",
        "wardrobe": "tailored olive tweed field jacket and leather riding boots",
        "mood": "refined heritage, HNCS 16-bit organic skin tones and tactile micro-relief",
        "timeWeather": "golden_hour",
        "lighting": "golden_hour",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_fujifilm_gfx100ii_reala": {
        "profile": "fujifilm_gfx100ii",
        "lens": "Fujinon GF 110mm f/2 R LM WR",
        "aperture": "f/2.8",
        "subject": "Master stone sculptor covered in fine marble dust on muscular forearms, chisel resting on Carrara relief",
        "framing": "three-quarter artisanal portrait",
        "environment": "historic Carrara limestone atelier with half-carved sculptures and raking morning sunbeams",
        "wardrobe": "heavy indigo canvas workshirt and stained leather apron",
        "mood": "intense concentration, raw craftsmanship, 102MP tonal graduation",
        "timeWeather": "morning_fog",
        "lighting": "window_daylight",
        "filmStock": "classic_chrome",
        "aspectRatio": "4:5",
    },
    "cam_fujifilm_gfx100ii_ts": {
        "profile": "fujifilm_gfx100ii",
        "lens": "Fujinon GF 30mm f/5.6 T/S",
        "aperture": "f/8.0",
        "subject": "medium format architectural photograph, 24mm-equivalent wide view, perspective-corrected with a shift lens so every vertical line stays parallel, level camera, deep focus front to back, high micro-detail, shot on Fujifilm GFX 100 II with GF 30mm T/S",
        "framing": "wide environmental architectural interior",
        "environment": "contemporary concrete museum interior with soaring vertical lines, smooth limestone flooring, and diffused clerestory illumination",
        "wardrobe": "none",
        "mood": "perspective-corrected shift lens acutance, zero vertical keystoning, edge-to-edge optical fidelity",
        "timeWeather": "overcast",
        "lighting": "architectural_skylight",
        "filmStock": "digital_raw",
        "aspectRatio": "4:3",
    },
    "cam_fujifilm_gfx100rf_street": {
        "profile": "fujifilm_gfx100rf",
        "lens": "Fujinon GF 45mm f/2.8 R WR",
        "aperture": "f/5.6",
        "subject": "Documentary photographer standing watchful on rain-slicked city crossing, camera resting at hip",
        "framing": "environmental street portrait",
        "environment": "rain-soaked European pedestrian plaza with historic stone facades and reflections",
        "wardrobe": "charcoal waxed cotton coat and leather boots",
        "mood": "fixed-lens medium format acutance, zero optical distortion, archival realism",
        "timeWeather": "rainy_wet",
        "lighting": "window_daylight",
        "filmStock": "classic_chrome",
        "aspectRatio": "4:3",
    },

    # 2. Leica Rangefinders & Precision Optics
    "cam_leica_m11_reportage": {
        "profile": "leica_m11",
        "lens": "Leica Summilux-M 35mm f/1.4 ASPH FLE II",
        "aperture": "f/2.8",
        "subject": "Pedestrian walking past an outdoor cafe terrace, holding an espresso cup",
        "framing": "three-quarter street editorial portrait",
        "environment": "wet cobblestone Paris street in Saint-Germain, limestone Haussmann facade in background",
        "wardrobe": "tailored navy wool trench coat and gray cashmere scarf",
        "mood": "effortless, contemplative, authentic Parisian elegance",
        "timeWeather": "overcast",
        "cityVibe": "paris",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_leica_m11_noctilux": {
        "profile": "leica_m11",
        "lens": "Leica Noctilux-M 50mm f/0.95 ASPH",
        "aperture": "f/1.4",
        "subject": "Jazz pianist paused at grand piano keys in intimate low-lit lounge, glistening lacquer reflections",
        "framing": "tight atmospheric portrait with razor-thin depth of field",
        "environment": "intimate jazz club with warm amber filament wall sconces and dark velvet curtains",
        "wardrobe": "crisp white unbuttoned collar shirt and dark wool vest",
        "mood": "The King of Light, dreamy subject isolation, luminous specular falloff",
        "timeWeather": "night_city",
        "lighting": "tungsten_candle",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_leica_m6_analog_trix": {
        "profile": "leica_m6_analog",
        "lens": "Leica Summicron-M 50mm f/2 Dual-Range",
        "aperture": "f/2.0",
        "subject": "City commuter under umbrella standing by crosswalk, raindrops caught in light",
        "framing": "medium close-up street documentary portrait",
        "environment": "narrow rain-soaked Shinjuku alley with glowing neon signs and reflective puddles",
        "wardrobe": "dark oversized trench coat with glistening raindrops on shoulders",
        "mood": "authentic 35mm silver halide grain, gritty timeless Magnum photojournalism",
        "timeWeather": "rainy_wet",
        "cityVibe": "tokyo",
        "lighting": "tungsten_candle",
        "filmStock": "tri_x_400",
        "aspectRatio": "3:2",
    },
    "cam_leica_m6_cinestill_800t": {
        "profile": "leica_m6_analog",
        "lens": "Leica Summilux-M 35mm f/1.4 Pre-ASPH 'Steel Rim'",
        "aperture": "f/1.4",
        "subject": "35mm color film photograph at night, 35mm lens wide open, tungsten-balanced negative, red-orange halation glowing around every light source, visible film grain, tungsten and neon light sources in frame, shot on Leica M6 with CineStill 800T",
        "framing": "medium close-up street documentary portrait",
        "environment": "rain-soaked Tokyo neon alleyway with glowing signs, wet reflective asphalt, and tungsten streetlamps",
        "wardrobe": "weathered dark leather coat with raindrops glistening",
        "mood": "authentic CineStill 800T remjet-removed red halation, 3200K tungsten balance, organic silver halide grain",
        "timeWeather": "night_city",
        "lighting": "neon",
        "filmStock": "cinestill_800t",
        "aspectRatio": "3:2",
    },
    "cam_leica_q3_monochrom": {
        "profile": "leica_q3_monochrom",
        "lens": "Leica Summilux 28mm f/1.7 ASPH",
        "aperture": "f/2.8",
        "subject": "Portrait of veteran silversmith with deep character wrinkles and intense focused gaze at jeweler bench",
        "framing": "intimate environmental craftsman portrait",
        "environment": "antique goldsmith workshop with scattered burins, silver wire, and raking north skylight",
        "wardrobe": "charcoal linen apron over textured gray work shirt",
        "mood": "zero Color Filter Array, uncompromised pure luminance micro-contrast, obsidian black to specular white",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_leica_sl2_motion_blur": {
        "profile": "leica_sl2",
        "lens": "Leica Summilux-SL 50mm f/1.4 ASPH",
        "aperture": "f/2.8",
        "subject": "Stationary traveler standing serenely still and tack-sharp at eye level while rushing crowd blurs around them",
        "framing": "wide environmental transit hall portrait",
        "environment": "grand European railway station concourse with streaming commuters in multi-directional motion blur trails",
        "wardrobe": "tailored camel wool coat and leather weekender bag",
        "mood": "calm center of gravity amidst swirling urban momentum, slow shutter motion-blur aesthetic",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_leica_sl3_p_apo": {
        "profile": "leica_sl3_p",
        "lens": "Leica APO-Summicron-SL 50mm f/2 ASPH",
        "aperture": "f/2.0",
        "subject": "Foreign correspondent standing on rain-spattered hotel balcony reviewing investigative notes",
        "framing": "three-quarter documentary portrait",
        "environment": "European capital city skyline under stormy twilight sky, wet railings and distant city lights",
        "wardrobe": "dark navy waterproof shell over fine charcoal sweater",
        "mood": "apochromatic optical acutance, zero chromatic aberration, foreign dispatch reportage tonal depth",
        "timeWeather": "blue_hour",
        "lighting": "blue_hour",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_leica_sl3_p_apo_90mm": {
        "profile": "leica_sl3_p",
        "lens": "Leica APO-Summicron-SL 90mm f/2 ASPH",
        "aperture": "f/2.0",
        "subject": "Editorial telephoto portrait of an architect standing thoughtfully on concrete observation cantilever overlooking misty cityscape",
        "framing": "tight telephoto editorial portrait with tack-sharp facial feature compression",
        "environment": "brutalist concrete museum terrace with low fog drifting over city below",
        "wardrobe": "tailored charcoal wool turtleneck and minimalist steel-frame spectacles",
        "mood": "apochromatic telephoto benchmark acutance, razor-sharp eyelashes, buttery optical background dissolution",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_leica_m11_noctilux_75mm": {
        "profile": "leica_m11",
        "lens": "Leica Noctilux-M 75mm f/1.25 ASPH",
        "aperture": "f/1.25",
        "subject": "Intimate low-light portrait of a cellist resting chin on instrument during evening rehearsal intermission",
        "framing": "tight atmospheric portrait with ultra-shallow depth of field and velvety bokeh discs",
        "environment": "amber-lit chamber hall with polished parquet flooring and dark velvet acoustic curtains",
        "wardrobe": "black silk evening shirt with open collar",
        "mood": "The King of Light telephoto, breathtaking subject isolation, creamy specular highlight roll-off",
        "timeWeather": "night_city",
        "lighting": "tungsten_candle",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_leica_m11_summicron_90mm": {
        "profile": "leica_m11",
        "lens": "Leica APO-Summicron-M 90mm f/2 ASPH",
        "aperture": "f/2.8",
        "subject": "Street flaneur walking across rain-slicked boulevard in evening twilight, reflected neon in puddles",
        "framing": "telephoto street portrait with compressed perspective",
        "environment": "rain-swept European boulevard with limestone Haussmann facades and warm bistro glows",
        "wardrobe": "navy cashmere overcoat and dark wool scarf",
        "mood": "telephoto street compression, tack-sharp focal plane, classic Magnum reportage acutance",
        "timeWeather": "rainy_wet",
        "lighting": "blue_hour",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_leica_m11_summicron_apo_50mm": {
        "profile": "leica_m11",
        "lens": "Leica APO-Summicron-M 50mm f/2 ASPH",
        "aperture": "f/2.8",
        "subject": "Master watchmaker examining balance assembly through loupe in warm timber atelier",
        "framing": "medium-close documentary portrait with extreme micro-contrast",
        "environment": "artisan horology bench with brass gears, precision tweezers, and north-facing diffused skylight",
        "wardrobe": "natural oatmeal linen shirt with rolled sleeves",
        "mood": "benchmark German optical micro-contrast, crisp tactile edge separation, authentic rangefinder acutance",
        "timeWeather": "window_daylight",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_leica_m11_summilux_35mm_asph_ii": {
        "profile": "leica_m11",
        "lens": "Leica Summilux-M 35mm f/1.4 ASPH II",
        "aperture": "f/2.0",
        "subject": "Documentary photojournalist holding vintage field journal at sidewalk cafe table",
        "framing": "classic environmental 35mm rangefinder portrait",
        "environment": "historic Latin Quarter cafe terrace with limestone facades and morning espresso steam",
        "wardrobe": "olive waxed field jacket over dark charcoal knit",
        "mood": "legendary 35mm reportage character, authentic micro-contrast, zero optical distortion",
        "timeWeather": "morning_golden",
        "lighting": "golden_hour",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },

    # 3. Wildlife & Extreme Telephoto Systems
    "cam_nikon_z9_tele_wildlife": {
        "profile": "nikon_z9",
        "lens": "NIKKOR Z 600mm f/4 TC VR S @ 840mm f/5.6",
        "aperture": "f/5.6",
        "subject": "super-telephoto wildlife photograph at 840mm, strong perspective compression, subject isolated against smooth blur, fast shutter freezing motion, full-frame clarity, shot on Nikon Z 9 with NIKKOR Z 600mm TC",
        "framing": "telephoto wildlife portrait",
        "environment": "subarctic tundra bluff with dry blowing snow and distant muted mountain horizon",
        "wardrobe": "none",
        "mood": "840mm extreme perspective compression, instantaneous action motion freeze, creamy background dissolution",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "shutter": "sync_1600",
        "filmStock": "digital_raw",
        "aspectRatio": "3:2",
    },
    "cam_nikon_z9_plena": {
        "profile": "nikon_z9",
        "lens": "NIKKOR Z 135mm f/1.8 S Plena (Zero Vignetting Texture Monster)",
        "aperture": "f/1.8",
        "subject": "Cellist seated in deep concentration during rehearsal, natural window backlight rimming hair",
        "framing": "medium seated performance portrait",
        "environment": "wood-paneled concert hall chamber with warm timber acoustic baffles",
        "wardrobe": "dark tailored charcoal wool suit",
        "mood": "Plena zero-vignetting edge-to-edge circular bokeh, velvety separation, tack-sharp cello strings",
        "timeWeather": "window_daylight",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },

    # 4. Hollywood Cinema & 65mm Motion Picture
    "cam_imax_msm_9802_bw": {
        "profile": "imax_msm_9802",
        "lens": "IMAX 65mm Large-Format Prime Lens",
        "aperture": "f/4.0",
        "subject": "black-and-white 65mm large-format motion picture film frame, monumental close-up of a face, extremely fine grain, rich silver tonal range, shot on IMAX 65mm film with Kodak Double-X",
        "framing": "monumental close-up portrait",
        "environment": "stark dramatic studio setting with deep shadow falloff and single high-intensity key light",
        "wardrobe": "textured dark wool high-collar coat",
        "mood": "15-perf 65mm horizontal motion picture film grandeur, immense IMAX negative scale, Kodak Double-X 5222 silver tonal latitude",
        "timeWeather": "night_city",
        "lighting": "rembrandt_key",
        "filmStock": "tri_x_400",
        "aspectRatio": "4:3",
    },
    "cam_arri_alexa_265_vista": {
        "profile": "arri_alexa_265",
        "lens": "ARRI Rental Prime 65 S 50mm T1.8",
        "aperture": "f/2.8",
        "subject": "large-format 65mm digital cinema frame, vast wide vista with immense detail, clean low-noise image, gentle highlight roll-off, natural film-like color, shallow depth of field despite the wide view, shot on ARRI ALEXA 265",
        "framing": "wide environmental cinematic vista",
        "environment": "sweeping rugged mountain plateau under dramatic cinematic sky with low raking clouds and golden horizon",
        "wardrobe": "weathered expedition parka with fur-lined hood",
        "mood": "65mm digital cinema grandeur, 15 stops dynamic range, gentle organic highlight roll-off",
        "timeWeather": "golden_hour",
        "lighting": "golden_hour",
        "filmStock": "arri_logc4",
        "aspectRatio": "21:9",
    },
    "cam_arri_alexa_35_cooke": {
        "profile": "arri_alexa_35",
        "lens": "Cooke S4/i 50mm T2.0 Cine Prime ('The Cooke Look')",
        "aperture": "f/2.0",
        "subject": "Detective seated at corner booth of dim speakeasy holding tumbler, intense focused gaze",
        "framing": "cinematic medium close-up",
        "environment": "speakeasy cocktail lounge with warm amber backlighting, mahogany, and brass accents",
        "wardrobe": "vintage weathered leather bomber jacket over open-collar dark shirt",
        "mood": "The Cooke Look, 17 stops dynamic range, organic LogC4 highlight roll-off",
        "timeWeather": "night_city",
        "lighting": "rembrandt_key",
        "filmStock": "arri_logc4",
        "aspectRatio": "21:9",
    },
    "cam_arri_alexa_35_anamorphic": {
        "profile": "arri_alexa_35",
        "lens": "Atlas Orion 65mm T2.0 2x Anamorphic Prime (Oval Bokeh & Horizontal Flare)",
        "aperture": "f/2.0",
        "subject": "Cinematic operative standing on wet rain-slicked city avenue, intense focused stillness",
        "framing": "widescreen medium cinematic shot",
        "environment": "rain-soaked neon district with reflective wet asphalt and vertical anamorphic light streaks",
        "wardrobe": "dark distressed tactical trench coat",
        "mood": "2.0x horizontal optical squeeze, 2:1 vertical oval bokeh, cyan streak flares",
        "timeWeather": "rainy_wet",
        "cityVibe": "tokyo",
        "lighting": "neon",
        "filmStock": "arri_logc4",
        "aspectRatio": "21:9",
        "anamorphic": True,
        "squeeze": "2.0x",
        "streakFlare": "cyan_blue",
        "irisBlades": "14_blade_circular",
    },
    "cam_sony_fx_venice_noir": {
        "profile": "sony_fx_series",
        "lens": "Sony FE 50mm f/1.2 GM @ f/2.8 (Venice Cine Sweet Spot)",
        "aperture": "f/2.8",
        "subject": "Jazz saxophonist performing under single warm tungsten pool of light on dark club stage",
        "framing": "medium performance shot with deep shadows",
        "environment": "intimate cellar jazz club with brick arches, subtle haze, and warm spotlight",
        "wardrobe": "midnight blue velvet blazer and unbuttoned silk shirt",
        "mood": "Sony VENICE 2 color science, S-Cinetone organic skin rendering, 180-degree cinema shutter cadence",
        "timeWeather": "night_city",
        "lighting": "tungsten_candle",
        "filmStock": "digital_raw",
        "aspectRatio": "16:9",
    },

    # 5. Analog Sheet Film, Large & Medium Formats
    "cam_nikon_fm2_kodachrome": {
        "profile": "nikon_fm2",
        "lens": "AI-S Nikkor 105mm f/2.5",
        "aperture": "f/2.8",
        "subject": "35mm color slide film portrait, 105mm lens, natural available light from one soft side source, saturated deep reds and greens, dense rich shadows, fine slide-film grain, shot on Nikon FM2 with Kodachrome 64",
        "framing": "tight head and shoulders portrait",
        "environment": "weathered earthen doorway with soft natural light entering from one side and deep shadows behind",
        "wardrobe": "vibrant red and green woven textile head wrap with weathered frayed edges",
        "mood": "legendary slide film color saturation, punchy contrast, dense shadow depth, mechanical SLR acutance",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "provia_100f",
        "aspectRatio": "3:2",
    },
    "cam_contax_645_wedding": {
        "profile": "contax_645",
        "lens": "Carl Zeiss Planar T* 80mm f/2",
        "aperture": "f/2.0",
        "subject": "medium format color film photograph, 80mm lens wide open at f/2, extremely shallow depth of field, overexposed one stop for bright airy high-key tones, soft pastel color, creamy background blur, shot on Contax 645 with Fuji Pro 400H",
        "framing": "three-quarter fine art portrait",
        "environment": "sun-drenched open garden meadow with soft backlight filtering through olive branches",
        "wardrobe": "delicate embroidered ivory lace gown with trailing silk veil",
        "mood": "airy high-key wedding fine art, luminescent pastel greens and creamy highlights, Carl Zeiss Planar f/2 spherical dissolution",
        "timeWeather": "golden_hour",
        "lighting": "golden_hour",
        "filmStock": "portra_400",
        "aspectRatio": "4:3",
    },
    "cam_hasselblad_xpan_panorama": {
        "profile": "hasselblad_xpan",
        "lens": "Hasselblad 45mm f/4 for XPan",
        "aperture": "f/8.0",
        "subject": "35mm film panoramic photograph in an ultra-wide 2.7:1 frame, full-width negative not a crop, even corner-to-corner sharpness, natural film color and grain, shot on Hasselblad XPan",
        "framing": "ultra-wide panoramic landscape",
        "environment": "remote Nordic coastal shoreline with wet black volcanic sand, sea stacks, and breaking white surf",
        "wardrobe": "yellow waxed fisherman raincoat",
        "mood": "authentic 24x65mm dual-format panoramic negative, cinematic 2.7:1 geometry, uncropped optical breadth",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "classic_chrome",
        "aspectRatio": "21:9",
    },
    "cam_deardorff_8x10_portrait": {
        "profile": "deardorff_8x10",
        "lens": "Schneider Kreuznach Symmar-S 360mm f/6.8",
        "aperture": "f/11",
        "subject": "large-format 8x10 black-and-white portrait, frontal composition, extreme detail in skin/hair/clothing, black film edge border visible, soft even natural light, plain seamless white backdrop, shot on a Deardorff 8x10 with Tri-X",
        "framing": "monumental full-torso frontal portrait",
        "environment": "open shade outdoor studio with plain seamless white paper backdrop and black negative fill flags",
        "wardrobe": "heavy dark denim work jacket and distressed work shirt",
        "mood": "monumental 8x10 contact sharpness, raw human topography, archival silver gelatin tonality, authentic black film border",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "tri_x_400",
        "aspectRatio": "4:5",
    },
    "cam_antique_view_8x10_collodion": {
        "profile": "antique_view_8x10",
        "lens": "Uncoated Brass Petzval Lens ~300mm f/3.8",
        "aperture": "f/3.8",
        "subject": "wet-plate collodion photograph on glass, antique uncoated lens with soft uneven focus and dark vignetting, silver-toned monochrome, chemical pour marks and streaks at the plate edges, brooding atmosphere, made with an antique 8x10 camera and wet-plate collodion",
        "framing": "intimate gothic headshot portrait",
        "environment": "dark nineteenth-century parlor with heavy drapery and dusty ambient daylight",
        "wardrobe": "high-neck Victorian black lace collar and dark tailored velvet frock coat",
        "mood": "authentic wet-plate ambrotype, silver collodion emulsion pour artifacts, swirling Petzval field curvature, brooding haunting stillness",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "tri_x_400",
        "aspectRatio": "4:5",
    },
    "cam_linhof_4x5_architectural": {
        "profile": "linhof_technika_4x5",
        "lens": "Schneider Kreuznach Apo-Symmar 150mm f/5.6 L (Museum Reference)",
        "aperture": "f/11",
        "subject": "Museum director standing gracefully in grand central gallery flanked by classical sculptures",
        "framing": "full-length architectural fashion portrait",
        "environment": "soaring neoclassical museum rotunda with polished marble floor and fluted columns",
        "wardrobe": "bespoke charcoal three-piece suit with silk tie",
        "mood": "Scheimpflug optical plane alignment, zero vertical keystoning, Kodak Ektar 100 resolution",
        "timeWeather": "overcast",
        "lighting": "architectural_skylight",
        "filmStock": "portra_160",
        "aspectRatio": "4:5",
    },
    "cam_linhof_4x5_desert": {
        "profile": "linhof_technika_4x5",
        "lens": "Rodenstock Grandagon-N 90mm f/4.5 (Extreme Architectural Rise)",
        "aperture": "f/16",
        "subject": "Explorer standing at canyon rim looking into the vast expanse of red sandstone",
        "framing": "wide environmental cinematic frame",
        "environment": "red sandstone canyon rim with deep geological strata and distant desert haze",
        "wardrobe": "khaki canvas safari jacket and wide-brim felt hat",
        "mood": "monumental scale, ancient earth, sheet film micro-acutance, adventurous stillness",
        "timeWeather": "noon_sun",
        "lighting": "golden_hour",
        "filmStock": "provia_100f",
        "aspectRatio": "4:5",
    },
    "cam_pentax_67_bokeh_king": {
        "profile": "pentax_67ii",
        "lens": "SMC Pentax 67 105mm f/2.4 (The Legendary Bokeh King)",
        "aperture": "f/2.4",
        "subject": "Person standing amidst wild sea grass with evening wind blowing through hair",
        "framing": "three-quarter editorial portrait",
        "environment": "coastal sand dunes leading to an open ocean beach at low tide",
        "wardrobe": "chunky cream cable-knit wool sweater and weathered denim",
        "mood": "The Legendary Bokeh King, medium format 6x7 negative depth, velvety background melt",
        "timeWeather": "golden_hour",
        "lighting": "golden_hour",
        "filmStock": "portra_400",
        "aspectRatio": "4:5",
    },
    "cam_pentax_67_cotswolds": {
        "profile": "pentax_67ii",
        "lens": "SMC Pentax 67 90mm f/2.8 (Crisp Documentary Normal)",
        "aperture": "f/2.8",
        "subject": "Botanist gathering garden roses into a wicker basket beside weathered stone wall",
        "framing": "three-quarter editorial portrait",
        "environment": "English country stone cottage garden overflowing with climbing roses and delphiniums",
        "wardrobe": "waxed cotton jacket and sage linen dress",
        "mood": "pastoral, romantic, gentle morning tranquility, organic Portra color palette",
        "timeWeather": "overcast",
        "lighting": "window_daylight",
        "filmStock": "portra_160",
        "aspectRatio": "4:5",
    },
    "cam_hasselblad_500cm_zeiss": {
        "profile": "hasselblad_500cm",
        "lens": "Carl Zeiss Planar T* 80mm f/2.8 CF (Legendary Standard)",
        "aperture": "f/4.0",
        "subject": "Winemaker inspecting grape clusters in late summer light along vineyard terrace",
        "framing": "square medium format environmental portrait",
        "environment": "sun-drenched Tuscan vineyard on rolling hills with cypress trees in background",
        "wardrobe": "rustic chambray shirt and dirt-stained leather work gloves",
        "mood": "Zeiss Planar micro-contrast, square 6x6 medium format discipline, sun-drenched Tuscany",
        "timeWeather": "golden_hour",
        "cityVibe": "mediterranean",
        "lighting": "golden_hour",
        "filmStock": "portra_400",
        "aspectRatio": "1:1",
    },

    # 6. Iconic Compacts & Street Documentary
    "cam_contax_t2_candid": {
        "profile": "contax_t2",
        "lens": "Carl Zeiss Sonnar T* 38mm f/2.8",
        "aperture": "f/2.8",
        "subject": "35mm point-and-shoot film snapshot, bright flash-lit subject falling off into a dark background, crisp contrast, casual candid framing, film grain, harsh direct on-camera flash at night, shot on Contax T2",
        "framing": "spontaneous candid party portrait",
        "environment": "dimly lit loft party after-hours with dark background falloff",
        "wardrobe": "black leather jacket and silver hoop earrings",
        "mood": "authentic late-night direct flash snapshot, Zeiss Sonnar contrast, instant pop aesthetic",
        "timeWeather": "night_city",
        "lighting": "hard_flash",
        "filmStock": "portra_400",
        "aspectRatio": "3:2",
    },
    "cam_ricoh_gr_iv_street": {
        "profile": "ricoh_gr_iv",
        "lens": "GR Lens 18.3mm f/2.8",
        "aperture": "f/5.6",
        "subject": "28mm wide street snapshot from a pocket camera, close quarters, deep zone focus, punchy high contrast, gritty texture, slightly spontaneous framing, shot on Ricoh GR IV",
        "framing": "dynamic low-angle street snapshot",
        "environment": "bustling metropolitan crosswalk with pedestrians caught mid-stride and bold architectural shadows",
        "wardrobe": "dark trench coat and sneakers",
        "mood": "decisive snap-focus documentary, high-contrast black-and-white street energy, pocket camera spontaneity",
        "timeWeather": "noon_sun",
        "lighting": "window_daylight",
        "filmStock": "tri_x_400",
        "aspectRatio": "3:2",
    },

    # 7. Aerial & Nadir Geometry
    "cam_dji_mavic_4_pro_nadir": {
        "profile": "dji_mavic_4_pro",
        "lens": "Hasselblad 28mm-equivalent f/2.8 Aerial Optics",
        "aperture": "f/4.0",
        "subject": "straight-down nadir aerial photograph from a drone, flat graphic geometry of the ground, no horizon, crisp detail across the frame, clean natural color, shot on DJI Mavic 4 Pro",
        "framing": "top-down 90-degree nadir aerial frame",
        "environment": "coastal shoreline intersection where turquoise ocean waves break against geometric basalt sea cliffs and winding road",
        "wardrobe": "none",
        "mood": "pure graphic planar composition, zero perspective convergence, 100MP Hasselblad aerial color fidelity",
        "timeWeather": "noon_sun",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "4:3",
    },

    # 8. Skin, Eyes & Hyperreal Portrait Masters
    "cam_canon_eos_r5_ii_macro_iris": {
        "profile": "canon_eos_r5_ii",
        "lens": "Canon RF 100mm f/2.8L Macro IS USM",
        "aperture": "f/11",
        "subject": "extreme 1.4x macro photograph of a human eye, iris fibers and crypts in sharp detail, individual eyelashes and fine skin texture around the lid, focus-stacked so the whole iris is sharp, crisp catchlight on the cornea, shot on Canon R5 Mark II with RF 100mm macro",
        "framing": "extreme macro iris and skin detail portrait",
        "environment": "controlled studio macro bench with dedicated corneal catchlight",
        "wardrobe": "none",
        "mood": "1.4x optical magnification, focus-stacked iris crypts and ciliary zone, micro-capillary eyelid detail",
        "timeWeather": "auto",
        "lighting": "strobe_softbox",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_mamiya_rz67_kino_flo": {
        "profile": "mamiya_rz67",
        "lens": "Mamiya Sekor Z 140mm f/4.5 Macro",
        "aperture": "f/5.6",
        "subject": "tight medium format color film portrait, face filling the frame, twin vertical catchlights making the eyes shine, even frontal light revealing every pore and wrinkle, neutral expression, plain background, two soft fluorescent light banks on both sides of the face, shot on Mamiya RZ67 with Portra 800",
        "framing": "tight character headshot",
        "environment": "minimalist dark studio background with twin vertical Kino Flo fluorescent soft banks flanking the camera",
        "wardrobe": "charcoal crewneck sweater",
        "mood": "unsparing character portraiture, twin vertical fluorescent corneal catchlights, medium format 6x7 tonal gradation",
        "timeWeather": "auto",
        "lighting": "window_daylight",
        "filmStock": "portra_400",
        "aspectRatio": "4:5",
    },
    "cam_polaroid_20x24_contact": {
        "profile": "polaroid_20x24",
        "lens": "Schneider 600mm f/11 for Polaroid 20x24",
        "aperture": "f/11",
        "subject": "giant 20x24 inch instant color photograph, life-size head portrait with no enlargement, extraordinary detail showing translucency of individual hairs and full skin topography, deeply saturated instant-film color, shot on a Polaroid 20x24 camera",
        "framing": "life-size 20x24 inch contact portrait",
        "environment": "mammoth studio camera room with neutral backdrop and high-output flash banks",
        "wardrobe": "dark textured woolen jacket",
        "mood": "monumental 1:1 contact optical scale, un-enlarged translucent hair strands, rich saturated Polacolor dye transfer",
        "timeWeather": "auto",
        "lighting": "strobe_para",
        "filmStock": "provia_100f",
        "aspectRatio": "4:5",
    },
    "cam_canon_eos_r5_ii_vogue_soft": {
        "profile": "canon_eos_r5_ii",
        "lens": "Canon RF 85mm F1.2L USM (Reference Portrait Prime)",
        "aperture": "f/1.4",
        "subject": "Beauty editorial model with sculptural wet-look hair, radiant luminous skin, and piercing direct gaze",
        "framing": "tight beauty headshot",
        "environment": "warm sand-colored studio seamless backdrop with diffused beauty dish key light",
        "wardrobe": "minimalist nude silk bandeau top",
        "mood": "legendary Canon skin tone warmth, creamy background defocus, tack-sharp eyelashes, soft sculptural beauty",
        "timeWeather": "auto",
        "lighting": "beauty_dish",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_canon_eos_r5_ii_vogue_texture": {
        "profile": "canon_eos_r5_ii",
        "lens": "Canon RF 85mm F1.2L USM (Reference Portrait Prime)",
        "aperture": "f/8.0",
        "subject": "Beauty editorial model with sculptural hair, authentic human skin texture with resolved micro-pores and fine vellus hair, piercing direct gaze",
        "framing": "tight beauty headshot",
        "environment": "warm sand-colored studio seamless backdrop with crisp beauty dish key light and white bounce",
        "wardrobe": "minimalist nude silk bandeau top",
        "mood": "deep depth of field (~136mm DOF) resolving micro-pore architecture and unyielding dermal realism across entire facial plane",
        "timeWeather": "auto",
        "lighting": "beauty_dish",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_canon_eos_r5_ii_vogue": {
        "profile": "canon_eos_r5_ii",
        "lens": "Canon RF 85mm F1.2L USM (Reference Portrait Prime)",
        "aperture": "f/1.4",
        "subject": "Beauty editorial model with sculptural wet-look hair, radiant luminous skin, and piercing direct gaze",
        "framing": "tight beauty headshot",
        "environment": "warm sand-colored studio seamless backdrop with diffused beauty dish key light",
        "wardrobe": "minimalist nude silk bandeau top",
        "mood": "legendary Canon skin tone warmth, creamy background defocus, tack-sharp eyelashes",
        "timeWeather": "auto",
        "lighting": "beauty_dish",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },

    # 9. Flagship Stacked & High-Resolution Systems
    "cam_sony_a1_ii_flash_freeze": {
        "profile": "sony_a1_ii",
        "lens": "Sony FE 85mm F1.4 GM II (SEL85F14GM2)",
        "aperture": "f/2.8",
        "subject": "Fencing athlete paused between lunges, perspiration glistening on brow, tack-sharp near-eye pupil focus",
        "framing": "three-quarter athletic editorial portrait",
        "environment": "minimalist dark gymnasium with high directional strobe freeze and black negative fill",
        "wardrobe": "white textured fencing jacket with foil blade resting vertically",
        "mood": "1/400s electronic stacked shutter freeze, brutal near-eye sharpness, zero motion blur",
        "timeWeather": "auto",
        "lighting": "strobe_para",
        "filmStock": "digital_raw",
        "aspectRatio": "9:11",
    },
    "cam_sony_a7rv_macro_horology": {
        "profile": "sony_a7rv",
        "lens": "Sony FE 90mm f/2.8 Macro G OSS",
        "aperture": "f/2.8",
        "subject": "Senior watchmaker looking through brass loupe, placing tourbillon balance wheel with titanium tweezers",
        "framing": "extreme macro iris and skin detail portrait",
        "environment": "cluttered antique wooden workbench with miniature gear wheels and micro-screwdrivers",
        "wardrobe": "dark wool vest and rolled-up striped cotton shirt",
        "mood": "61MP microscopic precision, resolved epidermal pores, true 1:1 macro brass tooth reflections",
        "timeWeather": "auto",
        "lighting": "strobe_para",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_sony_a7rv_depixel_flat": {
        "profile": "sony_a7rv",
        "lens": "Sony FE 50mm f/1.2 GM (SEL50F12GM)",
        "aperture": "f/5.6",
        "subject": "High-resolution flat archival document reproduction and infographic restoration with crisp typography",
        "framing": "perpendicular flat copy-stand reproduction",
        "environment": "professional copy-stand studio with balanced 45-degree polarized illumination",
        "wardrobe": "none",
        "mood": "Universal De-Pixelate v2.0 protocol, zero geometric distortion, strict OCR typography preservation",
        "timeWeather": "studio_soft",
        "lighting": "strobe_softbox",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
    "cam_canon_eos_r1_action": {
        "profile": "canon_eos_r1",
        "lens": "Canon RF 70-200mm F2.8L IS USM Z (Action & Sports Master)",
        "aperture": "f/2.8",
        "subject": "Prima ballerina caught at the floating zenith of a grand jeté leap across sunlit stage floor",
        "framing": "dynamic full-body performance framing",
        "environment": "historic opera house rehearsal hall with tall arched windows and dusty light shafts",
        "wardrobe": "dusty rose rehearsal tulle skirt and fitted black leotard",
        "mood": "stacked full-frame instantaneous motion freeze, decisive peak moment, athletic elegance",
        "timeWeather": "window_daylight",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "16:9",
    },
    "cam_panasonic_s1rii_micro": {
        "profile": "panasonic_lumix_s1rii",
        "lens": "Lumix S 100mm f/2.8 Macro (1:1 Micro-Detail Specialist)",
        "aperture": "f/5.6",
        "subject": "Botanical taxonomist dissecting rare cloud forest orchid petal with surgical micro-tweezers",
        "framing": "1:1 macro scientific portrait",
        "environment": "botany research laboratory bench with specimen glass jars and natural north daylight",
        "wardrobe": "crisp white laboratory coat and dark slate glasses",
        "mood": "micro-science optical purity, cellular petal vein relief, tactile pollen grains",
        "timeWeather": "window_daylight",
        "lighting": "window_daylight",
        "filmStock": "digital_raw",
        "aspectRatio": "4:5",
    },
}

LENS_PRESETS = LENS_CATALOG
OPTICAL_PRESETS = CAMERA_PRESETS

